INSERT INTO USER (USERNAME, NAME, LOCATION) VALUES ('Jkessl204', 'Josh Kessler', 'Philadelphia');
INSERT INTO USER (USERNAME, NAME, LOCATION) VALUES ('realDonaldTrump', 'Donald J. Trump', 'White House');
INSERT INTO USER (USERNAME, NAME, LOCATION) VALUES ('notoriousRBG', 'Ruth Bader Ginsberg', '');
INSERT INTO USER (USERNAME, NAME, LOCATION) VALUES ('iluvcomcast', 'Brian Roberts', 'Pennsylvania');
INSERT INTO USER (USERNAME, NAME, LOCATION) VALUES ('HillaryClinton', 'Hillary Cliton', 'The Woods');
INSERT INTO USER (USERNAME, NAME, LOCATION) VALUES ('YaasGaga', 'Lady Gaga', '');
INSERT INTO USER (USERNAME, NAME, LOCATION) VALUES ('PortugalTourism', '', 'Lisbon');
INSERT INTO USER (USERNAME, NAME, LOCATION) VALUES ('secretadmirer', '', 'Right behind you');


INSERT INTO FOLLOWING (FOLLOWER_ID, FOLLOWEE_ID) VALUES((SELECT USER_ID FROM USER WHERE USERNAME = 'realDonaldTrump'), (SELECT USER_ID FROM USER WHERE USERNAME = 'HillaryClinton');
INSERT INTO FOLLOWING (FOLLOWER_ID, FOLLOWEE_ID) VALUES((SELECT USER_ID FROM USER WHERE USERNAME = 'iluvcomcast'), (SELECT USER_ID FROM USER WHERE USERNAME = 'YaasGaga');
INSERT INTO FOLLOWING (FOLLOWER_ID, FOLLOWEE_ID) VALUES((SELECT USER_ID FROM USER WHERE USERNAME = 'Jkessl204'), (SELECT USER_ID FROM USER WHERE USERNAME = 'PortugalTourism');
INSERT INTO FOLLOWING (FOLLOWER_ID, FOLLOWEE_ID) VALUES((SELECT USER_ID FROM USER WHERE USERNAME = 'realDonaldTrump'), (SELECT USER_ID FROM USER WHERE USERNAME = 'notoriousRBG');
INSERT INTO FOLLOWING (FOLLOWER_ID, FOLLOWEE_ID) VALUES((SELECT USER_ID FROM USER WHERE USERNAME = 'notoriousRBG'), (SELECT USER_ID FROM USER WHERE USERNAME = 'YaasGaga');

INSERT INTO TWEET (WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT USER_ID FROM USER WHERE USERNAME = 'realDonaldTrump'), 'I AM GOING TO BUILD THE WALL IT IS SUCH AN EMERGENCY. #MAGA', 2019-02-15 01:00:00);
INSERT INTO TWEET (WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT USER_ID FROM USER WHERE USERNAME = 'Jkessl204'), 'I should stop working on this and go to bed', 2019-02-23 00:55:00);
INSERT INTO TWEET (WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT USER_ID FROM USER WHERE USERNAME = 'YaasGaga'), 'If the Academy does not recognize my talent tonight it shows they are sha-ah-ah-ah-ahllow', 2019-02-24 12:00:00);
INSERT INTO TWEET (WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT USER_ID FROM USER WHERE USERNAME = 'HillaryClinton'), 'I am hungry.', 2019-02-20 11:55:00);
INSERT INTO TWEET (WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT USER_ID FROM USER WHERE USERNAME = 'HillaryClinton'), 'Fear not, I had a grilled cheese.', 2019-02-20 12:30:00);

INSERT INTO COMMENT (ORIGINAL_TWEET_ID, WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT TWEET_ID FROM TWEET WHERE USERNAME = 'YaasGaga'), (SELECT USER_ID FROM USER WHERE USERNAME = 'notoriousRBG'), 'I am staging a writein campaign for Felicity Jones', 2019-02-24 14:00:00);
INSERT INTO COMMENT (ORIGINAL_TWEET_ID, WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT TWEET_ID FROM TWEET WHERE USERNAME = 'YaasGaga'), (SELECT USER_ID FROM USER WHERE USERNAME = 'iluvcomcast'), 'Rooting for you!', 2019-02-24 14:01:00);
INSERT INTO COMMENT (ORIGINAL_TWEET_ID, WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT TWEET_ID FROM TWEET WHERE MESSAGE_TEXT = 'I am hungry.'), (SELECT USER_ID FROM USER WHERE USERNAME = 'realDonaldTrump'), 'Not hungry, crooked', 2019-02-20 11:55:10);
INSERT INTO COMMENT (ORIGINAL_TWEET_ID, WRITTEN_BY, MESSAGE_TEXT, TIMESTAMP) VALUES ((SELECT TWEET_ID FROM TWEET WHERE MESSAGE_TEXT = 'Fear not, I had a grilled cheese.'), (SELECT USER_ID FROM USER WHERE USERNAME = 'realDonaldTrump'),, 'Hope you choke, just like you choked in the election in which MANY SAY I would have WON THE POPULAR VOTE if BAD MEN did not vote ILLEGALLY', 2019-02-20 12:30:01);