CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(15) NOT NULL UNIQUE,
  NAME VARCHAR(50),
  LOCATION VARCHAR(50)
);

CREATE TABLE FOLLOWING(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FOLLOWER_ID BIGINT,
  FOLLOWEE_ID BIGINT
);

CREATE TABLE TWEET(
  TWEET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  WRITTEN_BY BIGINT NOT NULL,
  MESSAGE_TEXT TEXT NOT NULL,
  TIMESTAMP DATETIME NOT NULL,
);

CREATE TABLE COMMENT(
  COMMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ORIGINAL_TWEET_ID BIGINT NOT NULL,
  WRITTEN_BY BIGINT NOT NULL,
  MESSAGE_TEXT TEXT NOT NULL,
  TIMESTAMP DATETIME NOT NULL,
);

ALTER TABLE FOLLOWING ADD FOREIGN KEY (FOLLOWER_ID) REFERENCES USER(USER_ID);
ALTER TABLE FOLLOWING ADD FOREIGN KEY (FOLLOWEE_ID) REFERENCES USER(USER_ID);
ALTER TABLE TWEET ADD FOREIGN KEY (WRITTEN_BY) REFERENCES USER(USER_ID);
ALTER TABLE COMMENT ADD FOREIGN KEY (ORIGINAL_TWEET_ID) REFERENCES TWEET(TWEET_ID);
ALTER TABLE COMMENT ADD FOREIGN KEY (WRITTEN_BY) REFERENCES USER(USER_ID);
